// Insert Estado de Cuenta JS into HTML
// All CSS var() strings use escaped double quotes to avoid single-quote conflicts
const fs = require('fs');
let c = fs.readFileSync('G:/Mi unidad/ERP/hestia-fertility-dashboard.html', 'utf8');

// Build the JS as array of lines then join - avoids template literal issues
var lines = [
'',
'/* =====================================================================',
'   ESTADO DE CUENTA -- busqueda, render y print',
'   ===================================================================== */',
'',
'var _ecData = null;',
'var _ecPacientesList = [];',
'var _ecMovAll = [];',
'',
'function ecInit() {',
'  if (_ecPacientesList.length) return;',
'  var tok = getToken();',
'  fetch(APPS_SCRIPT_URL + "?action=listaPacientes&token=" + encodeURIComponent(tok) + "&_t=" + Date.now(), {redirect:"follow"})',
'    .then(function(r){ return r.json(); })',
'    .then(function(d){ if (d && d.pacientes) _ecPacientesList = d.pacientes.map(function(p){ return typeof p === "string" ? p : p.nombre; }); })',
'    .catch(function(){});',
'}',
'',
'function ecOnInput(val) {',
'  var box = document.getElementById("ec-suggestions");',
'  if (!box) return;',
'  if (!val || val.length < 2) { box.style.display = "none"; return; }',
'  var q = val.toLowerCase();',
'  var matches = _ecPacientesList.filter(function(n){ return n.toLowerCase().indexOf(q) >= 0; }).slice(0, 10);',
'  if (!matches.length) { box.style.display = "none"; return; }',
'  var html = "";',
'  for (var i = 0; i < matches.length; i++) {',
'    var n = matches[i];',
'    html += "<div class=\\"ec-sug-item\\" style=\\"padding:9px 14px;cursor:pointer;font-size:13px;color:var(--color-text);border-bottom:1px solid var(--color-divider)\\"" +',
'      " data-name=\\"" + n.replace(/"/g, "&quot;") + "\\">"+n+"</div>";',
'  }',
'  box.innerHTML = html;',
'  box.style.display = "block";',
'  var items = box.querySelectorAll(".ec-sug-item");',
'  for (var j = 0; j < items.length; j++) {',
'    items[j].addEventListener("mousedown", function(ev){ ecSeleccionar(ev.currentTarget.getAttribute("data-name")); });',
'    items[j].addEventListener("mouseover", function(ev){ ev.currentTarget.style.background = "var(--color-surface-2)"; });',
'    items[j].addEventListener("mouseout",  function(ev){ ev.currentTarget.style.background = ""; });',
'  }',
'}',
'',
'function ecSeleccionar(nombre) {',
'  var inp = document.getElementById("ec-search");',
'  if (inp) inp.value = nombre;',
'  var box = document.getElementById("ec-suggestions");',
'  if (box) box.style.display = "none";',
'  ecBuscar();',
'}',
'',
'function ecBuscar() {',
'  var nombre = (document.getElementById("ec-search") || {}).value || "";',
'  nombre = nombre.trim();',
'  if (!nombre) return;',
'  var box = document.getElementById("ec-suggestions");',
'  if (box) box.style.display = "none";',
'  document.getElementById("ec-loading").style.display = "";',
'  document.getElementById("ec-result").style.display = "none";',
'  document.getElementById("ec-error").style.display = "none";',
'  document.getElementById("ec-btn-print").style.display = "none";',
'  var tok = getToken();',
'  fetch(APPS_SCRIPT_URL + "?action=estadoCuenta&paciente=" + encodeURIComponent(nombre) + "&token=" + encodeURIComponent(tok) + "&_t=" + Date.now(), {redirect:"follow"})',
'    .then(function(r){ return r.json(); })',
'    .then(function(d){',
'      document.getElementById("ec-loading").style.display = "none";',
'      if (!d.ok) { document.getElementById("ec-error").textContent = d.error || "Error al consultar"; document.getElementById("ec-error").style.display = ""; return; }',
'      _ecData = d;',
'      _ecMovAll = d.movimientos || [];',
'      ecRenderResult(d);',
'    })',
'    .catch(function(e){',
'      document.getElementById("ec-loading").style.display = "none";',
'      document.getElementById("ec-error").textContent = "Error de red: " + e.message;',
'      document.getElementById("ec-error").style.display = "";',
'    });',
'}',
'',
'function ecFmt(n) {',
'  var sign = "$";',
'  return sign + (parseFloat(n)||0).toLocaleString("es-MX", {minimumFractionDigits:2, maximumFractionDigits:2});',
'}',
'',
'function ecFmtFecha(str) {',
'  if (!str) return "";',
'  var p = str.split("-");',
'  if (p.length < 3) return str;',
'  var meses = ["Ene","Feb","Mar","Abr","May","Jun","Jul","Ago","Sep","Oct","Nov","Dic"];',
'  return parseInt(p[2]) + " " + (meses[parseInt(p[1])-1]||p[1]) + " " + p[0];',
'}',
'',
'function ecRenderResult(d) {',
'  var cards = document.getElementById("ec-cards");',
'  var porAnioHtml = "";',
'  var anios = Object.keys(d.porAnio||{}).sort();',
'  for (var i = 0; i < anios.length; i++) {',
'    var a = anios[i];',
'    porAnioHtml += "<div style=\\"background:var(--color-surface-2);border-radius:8px;padding:10px 14px;text-align:center\\">"',
'      + "<div style=\\"font-size:10px;font-weight:700;text-transform:uppercase;color:var(--color-text-muted);margin-bottom:4px\\">" + a + "</div>"',
'      + "<div style=\\"font-size:14px;font-weight:700;color:var(--color-primary)\\">" + ecFmt(d.porAnio[a]) + "</div></div>";',
'  }',
'  cards.innerHTML = "<div style=\\"background:var(--color-primary);border-radius:10px;padding:14px 18px;color:#fff\\">"',
'    + "<div style=\\"font-size:10px;font-weight:700;opacity:.8;text-transform:uppercase;margin-bottom:4px\\">Total historico</div>"',
'    + "<div style=\\"font-size:22px;font-weight:800\\">" + ecFmt(d.totalGeneral) + "</div>"',
'    + "<div style=\\"font-size:11px;opacity:.75;margin-top:4px\\">" + d.totalMovimientos + " movimientos</div></div>"',
'    + porAnioHtml;',
'  document.getElementById("ec-tabla-titulo").textContent = "Movimientos de " + d.paciente;',
'  document.getElementById("ec-total-display").textContent = ecFmt(d.totalGeneral);',
'  ecRenderTabla(_ecMovAll);',
'  document.getElementById("ec-result").style.display = "";',
'  document.getElementById("ec-btn-print").style.display = "flex";',
'}',
'',
'function ecRenderTabla(movs) {',
'  var tbody = document.getElementById("ec-tbody");',
'  if (!movs.length) { tbody.innerHTML = "<tr><td colspan=\\"5\\" style=\\"padding:30px;text-align:center;color:var(--color-text-muted)\\">Sin movimientos</td></tr>"; return; }',
'  var html = "";',
'  for (var i = 0; i < movs.length; i++) {',
'    var m = movs[i];',
'    var bg = i%2===1 ? "background:var(--color-surface-2)" : "";',
'    html += "<tr style=\\"border-bottom:1px solid var(--color-divider);" + bg + "\\">"',
'      + "<td style=\\"padding:10px 14px;white-space:nowrap;color:var(--color-text-muted);font-size:12px\\">" + ecFmtFecha(m.fecha) + "</td>"',
'      + "<td style=\\"padding:10px 14px;color:var(--color-text);font-weight:500\\">" + (m.producto||m.desc||"--") + "</td>"',
'      + "<td style=\\"padding:10px 14px;color:var(--color-text-muted);font-size:12px\\">" + (m.cat||"--") + "</td>"',
'      + "<td style=\\"padding:10px 14px;color:var(--color-text-muted);font-size:12px\\">" + (m.pago||"--") + "</td>"',
'      + "<td style=\\"padding:10px 14px;text-align:right;font-weight:700;color:var(--color-text)\\">" + ecFmt(m.total) + "</td>"',
'      + "</tr>";',
'  }',
'  tbody.innerHTML = html;',
'}',
'',
'function ecFiltrarTabla(q) {',
'  if (!q) { ecRenderTabla(_ecMovAll); return; }',
'  q = q.toLowerCase();',
'  var filtered = _ecMovAll.filter(function(m){',
'    return (m.producto+m.cat+m.desc+m.pago+m.fecha).toLowerCase().indexOf(q) >= 0;',
'  });',
'  ecRenderTabla(filtered);',
'}',
'',
'function ecImprimir() {',
'  if (!_ecData) return;',
'  var cfg = getFmtConfig();',
'  var d = _ecData;',
'  var movs = _ecMovAll;',
'  var cp = cfg.colorPrimary;',
'  var ct = cfg.colorText;',
'  var sign = "$";',
'',
'  var rowsHtml = "";',
'  for (var i = 0; i < movs.length; i++) {',
'    var m = movs[i];',
'    var bg = i%2===1 ? "background:#fdf5f6" : "";',
'    rowsHtml += "<tr style=\\"border-bottom:1px solid #f0e6e8;" + bg + "\\">"',
'      + "<td style=\\"padding:9px 14px;font-size:12px;color:#888;white-space:nowrap\\">" + ecFmtFecha(m.fecha) + "</td>"',
'      + "<td style=\\"padding:9px 14px;font-size:13px;color:#333;font-weight:500\\">" + (m.producto||m.desc||"--") + "</td>"',
'      + "<td style=\\"padding:9px 14px;font-size:12px;color:#888\\">" + (m.cat||"--") + "</td>"',
'      + "<td style=\\"padding:9px 14px;font-size:12px;color:#888\\">" + (m.pago||"--") + "</td>"',
'      + "<td style=\\"padding:9px 14px;font-size:13px;font-weight:700;text-align:right;color:#333\\">" + ecFmt(m.total) + "</td>"',
'      + "</tr>";',
'  }',
'',
'  var resumenHtml = "";',
'  var ranios = Object.keys(d.porAnio||{}).sort();',
'  for (var j = 0; j < ranios.length; j++) {',
'    var ay = ranios[j];',
'    resumenHtml += "<div style=\\"background:#fdf5f6;border-radius:8px;padding:10px 14px;text-align:center;min-width:100px\\">"',
'      + "<div style=\\"font-size:10px;font-weight:700;color:#888;margin-bottom:3px\\">" + ay + "</div>"',
'      + "<div style=\\"font-size:14px;font-weight:700;color:" + cp + "\\">" + ecFmt(d.porAnio[ay]) + "</div></div>";',
'  }',
'',
'  var logoHtml = cfg.logo',
'    ? ("<img src=\\"" + cfg.logo + "\\" style=\\"height:52px;object-fit:contain;display:block\\" alt=\\"logo\\">") ',
'    : ("<div style=\\"font-size:22px;font-weight:800;color:" + cp + ";letter-spacing:-0.5px\\">" + cfg.nombre + "</div>");',
'',
'  var today = ecFmtFecha(new Date().toISOString().substring(0,10));',
'',
'  var doc = "";',
'  doc += "<!DOCTYPE html><html lang=\\"es\\"><head><meta charset=\\"UTF-8\\">";',
'  doc += "<title>Estado de Cuenta -- " + d.paciente + "</title>";',
'  doc += "<style>*{margin:0;padding:0;box-sizing:border-box}";',
'  doc += "body{font-family:\\"Helvetica Neue\\",Helvetica,Arial,sans-serif;color:" + ct + ";background:#fff;padding:32px}";',
'  doc += "@media print{body{padding:0}@page{margin:20mm 18mm}}";',
'  doc += "table{width:100%;border-collapse:collapse}";',
'  doc += "thead tr{background:" + cp + "}";',
'  doc += "thead th{padding:10px 14px;text-align:left;font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:.07em;color:#fff}";',
'  doc += "thead th:last-child{text-align:right}";',
'  doc += "</style></head><body>";',
'  doc += "<div style=\\"display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:28px;padding-bottom:20px;border-bottom:2.5px solid " + cp + "\\">";',
'  doc += "<div>" + logoHtml;',
'  doc += "<div style=\\"font-size:11px;color:#999;margin-top:8px;line-height:1.8\\">";',
'  doc += cfg.direccion + "<br>" + cfg.ciudad + "<br>" + cfg.telefono + " &middot; " + cfg.email;',
'  doc += "</div></div>";',
'  doc += "<div style=\\"text-align:right\\">";',
'  doc += "<div style=\\"font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.12em;color:#ccc;margin-bottom:6px\\">Estado de Cuenta</div>";',
'  doc += "<div style=\\"font-size:26px;font-weight:800;color:" + cp + ";letter-spacing:-0.5px\\">" + d.paciente + "</div>";',
'  doc += "<div style=\\"font-size:12px;color:#aaa;margin-top:4px\\">Emitido el " + today + "</div>";',
'  doc += "</div></div>";',
'  doc += "<div style=\\"display:flex;gap:12px;align-items:stretch;margin-bottom:28px;flex-wrap:wrap\\">";',
'  doc += "<div style=\\"background:" + cp + ";border-radius:10px;padding:14px 22px;color:#fff;min-width:160px\\">";',
'  doc += "<div style=\\"font-size:10px;font-weight:700;opacity:.8;margin-bottom:4px;text-transform:uppercase\\">Total historico</div>";',
'  doc += "<div style=\\"font-size:26px;font-weight:800\\">" + ecFmt(d.totalGeneral) + "</div>";',
'  doc += "<div style=\\"font-size:11px;opacity:.7;margin-top:3px\\">" + d.totalMovimientos + " movimientos</div></div>";',
'  doc += resumenHtml + "</div>";',
'  doc += "<table><thead><tr>";',
'  doc += "<th>Fecha</th><th>Concepto</th><th>Categoria</th><th>Forma de pago</th><th style=\\"text-align:right\\">Importe</th>";',
'  doc += "</tr></thead><tbody>" + rowsHtml + "</tbody></table>";',
'  doc += "<div style=\\"display:flex;justify-content:flex-end;padding:14px 0;border-top:2px solid " + cp + ";margin-top:0\\">";',
'  doc += "<div style=\\"font-size:15px;font-weight:700;color:" + ct + "\\">Total: ";',
'  doc += "<span style=\\"color:" + cp + ";font-size:18px\\">" + ecFmt(d.totalGeneral) + "</span></div></div>";',
'  if (cfg.frase) {',
'    doc += "<div style=\\"margin-top:28px;padding:18px 22px;border-left:4px solid " + cp + ";background:#fdf5f6;border-radius:0 8px 8px 0\\">";',
'    doc += "<p style=\\"font-style:italic;color:#888;font-size:13px;line-height:1.7\\">" + cfg.frase + "</p></div>";',
'  }',
'  doc += "<div style=\\"margin-top:24px;text-align:center;font-size:10px;color:#ccc;border-top:1px solid #f0e6e8;padding-top:12px\\">";',
'  doc += (cfg.notaPie || "Documento generado por Hestia ERP") + "</div>";',
'  doc += "</body></html>";',
'',
'  var win = window.open("", "_blank", "width=900,height=700");',
'  win.document.write(doc);',
'  win.document.close();',
'  setTimeout(function(){ win.print(); }, 600);',
'}',
''
];

var EC_JS = lines.join('\n');

// Hook ecInit into navigateTo for estado-cuenta view
// Find the renderView function to also call ecInit
// For now, just insert before last </script>
var BEFORE = ';\r\n})();\r\n</script>\r\n</body>';
if (c.indexOf(BEFORE) < 0) { console.error('MARKER NOT FOUND'); process.exit(1); }
c = c.replace(BEFORE, ';\r\n})();\r\n\r\n' + EC_JS + '\r\n</script>\r\n</body>');
fs.writeFileSync('G:/Mi unidad/ERP/hestia-fertility-dashboard.html', c, 'utf8');
console.log('EC JS inserted OK, file size:', c.length);
